BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEST.COMMENTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE TEST.COMMENTS
(
    COMMENT_COL VARCHAR(10)
)
/
COMMENT ON TABLE TEST.COMMENTS IS 'This is a table comment'
/
COMMENT ON COLUMN TEST.COMMENTS.COMMENT_COL IS 'This is a column comment'
