BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEST.NULLABILITY PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE TEST.NULLABILITY
(
    NULLABLE_COL     VARCHAR(10),
    NOT_NULLABLE_COL VARCHAR(10) NOT NULL
)