DROP TABLE IF EXISTS TEST.TEMPORAL_DATA_TYPES;
CREATE TABLE TEST.TEMPORAL_DATA_TYPES
(
    DATE_COL             DATE,

    TIME_COL             TIME,
    TIME_0_COL           TIME(0),
    TIME_1_COL           TIME(1),
    TIME_9_COL           TIME(9),

    TIME_WOTZ_COL        TIME WITHOUT TIME ZONE,
    TIME_0_WOTZ_COL      TIME(0) WITHOUT TIME ZONE,
    TIME_1_WOTZ_COL      TIME(1) WITHOUT TIME ZONE,
    TIME_9_WOTZ_COL      TIME(9) WITHOUT TIME ZONE,

    TIME_WTZ_COL         TIME WITH TIME ZONE,
    TIME_0_WTZ_COL       TIME(0) WITH TIME ZONE,
    TIME_1_WTZ_COL       TIME(1) WITH TIME ZONE,
    TIME_9_WTZ_COL       TIME(9) WITH TIME ZONE,

    TIMESTAMP_COL        TIMESTAMP,
    TIMESTAMP_0_COL      TIMESTAMP(0),
    TIMESTAMP_1_COL      TIMESTAMP(1),
    TIMESTAMP_9_COL      TIMESTAMP(9),

    TIMESTAMP_WOTZ_COL   TIMESTAMP WITHOUT TIME ZONE,
    TIMESTAMP_WOTZ_0_COL TIMESTAMP(0) WITHOUT TIME ZONE,
    TIMESTAMP_WOTZ_1_COL TIMESTAMP(1) WITHOUT TIME ZONE,
    TIMESTAMP_WOTZ_9_COL TIMESTAMP(9) WITHOUT TIME ZONE,

    TIMESTAMP_WTZ_COL    TIMESTAMP WITH TIME ZONE,
    TIMESTAMP_0_WTZ_COL  TIMESTAMP(0) WITH TIME ZONE,
    TIMESTAMP_1_WTZ_COL  TIMESTAMP(1) WITH TIME ZONE,
    TIMESTAMP_9_WTZ_COL  TIMESTAMP(9) WITH TIME ZONE,

    UUID_COL             UUID

)