DROP TABLE IF EXISTS TEST.CHAR_DATA_TYPES;
CREATE TABLE TEST.CHAR_DATA_TYPES
(
    -- with default size of 1 character
    CHAR_COL              CHAR,
    CHARACTER_COL         CHARACTER,
    NCHAR_COL             NCHAR,
    NATIONAL_CHAR         NATIONAL CHAR,
    NATIONAL_CHARACTER    NATIONAL CHARACTER,

    -- with size of 1 character
    CHAR_1_COL                  CHAR(1),
    CHAR_1_OCTETS_COL           CHARACTER(1 OCTETS),
    CHAR_1_CODEUNITS32_COL      CHAR(1 CODEUNITS32),

    CHARACTER_1_COL             CHARACTER(1),
    CHARACTER_1_OCTETS_COL      CHARACTER(1 OCTETS),
    CHARACTER_1_CODEUNITS32_COL CHARACTER(1 CODEUNITS32),

    VARCHAR_1_COL               VARCHAR(1),
    VARCHAR_1_OCTETS_COL        VARCHAR(1 OCTETS),
    VARCHAR_1_CODEUNITS32_COL   VARCHAR(1 CODEUNITS32),

    CHAR_VARCHAR_1_COL             CHAR VARYING(1),
    CHAR_VARCHAR_1_OCTETS_COL      CHAR VARYING(1 OCTETS),
    CHAR_VARCHAR_1_CODEUNITS32_COL CHAR VARYING(1 CODEUNITS32),

    CHARACTER_VARYING_1_COL             CHARACTER VARYING(1),
    CHARACTER_VARYING_1_OCTETS_COL      CHARACTER VARYING(1 OCTETS),
    CHARACTER_VARYING_1_CODEUNITS32_COL CHARACTER VARYING(1 CODEUNITS32),

    NCHAR_1_COL          NCHAR(1),
    NATIONAL_1_CHAR      NATIONAL CHAR(1),
    NATIONAL_1_CHARACTER NATIONAL CHARACTER(1),

    NVARCHAR_1_COL NVARCHAR(1),

    -- with maximum size
    CHAR_255_COL            CHAR(255),
    CHAR_255_OCTETS_COL     CHAR(255 OCTETS),
    CHAR_63_CODEUNITS32_COL CHAR(63 CODEUNITS32),

    CHARACTER_255_COL            CHARACTER(255),
    CHARACTER_255_OCTETS_COL     CHARACTER(255 OCTETS),
    CHARACTER_63_CODEUNITS32_COL CHARACTER(63 CODEUNITS32),

    VARCHAR_32672_COL            VARCHAR(32672),
    VARCHAR_32672_OCTETS_COL     VARCHAR(32672 OCTETS),
    VARCHAR_8168_CODEUNITS32_COL VARCHAR(8168 CODEUNITS32),

    NCHAR_63_COL              NCHAR(63),
    NATIONAL_CHAR_63_COL      NATIONAL CHAR(63),
    NATIONAL_CHARACTER_63_COL NATIONAL CHARACTER(63),

    NVARCHAR_8168_COL                   NVARCHAR(8168),
    NCHAR_VARYING_8168_COL              NCHAR VARYING(8168),
    NATIONAL_CHAR_VARYING_8168_COL      NATIONAL CHAR VARYING(8168),
    NATIONAL_CHARACTER_VARYING_8168_COL NATIONAL CHARACTER VARYING(8168),

    -- long varchar
    LONG_VARCHAR_COL      LONG VARCHAR
)
