DROP TABLE IF EXISTS TEST.NON_UNIQUE_INDEX_DESC
/
CREATE TABLE TEST.NON_UNIQUE_INDEX_DESC
(
    COL_1 VARCHAR(10) NOT NULL
)
/
CREATE INDEX TEST.NON_UNIQUE_IDX_DESC ON TEST.NON_UNIQUE_INDEX_DESC (COL_1 DESC)
/