DROP TABLE IF EXISTS TEST.NON_UNIQUE_INDEX_DESC_DESC
/
CREATE TABLE TEST.NON_UNIQUE_INDEX_DESC_DESC
(
    COL_1 VARCHAR(10) NOT NULL,
    COL_2 VARCHAR(10) NOT NULL
)
/
CREATE INDEX TEST.NON_UNIQUE_IDX_DESC_DESC ON TEST.NON_UNIQUE_INDEX_DESC_DESC (COL_1 DESC, COL_2 DESC)
/