DROP TABLE IF EXISTS TEST.UNIQUE_INDEX_DESC_DESC
/
CREATE TABLE TEST.UNIQUE_INDEX_DESC_DESC
(
    COL_1 VARCHAR(10) NOT NULL,
    COL_2 VARCHAR(10) NOT NULL
)
/
CREATE UNIQUE INDEX TEST.UNIQUE_IDX_DESC_DESC ON TEST.UNIQUE_INDEX_DESC_DESC (COL_1 DESC, COL_2 DESC)
/