DROP TABLE IF EXISTS TEST.NON_UNIQUE_INDEX_DESC_ASC
/
CREATE TABLE TEST.NON_UNIQUE_INDEX_DESC_ASC
(
    COL_1 VARCHAR(10) NOT NULL,
    COL_2 VARCHAR(10) NOT NULL
)
/
CREATE INDEX TEST.NON_UNIQUE_IDX_DESC_ASC ON TEST.NON_UNIQUE_INDEX_DESC_ASC (COL_1 DESC, COL_2 ASC)
/