DROP TABLE IF EXISTS TEST.UNIQUE_INDEX_ASC_ASC
/
CREATE TABLE TEST.UNIQUE_INDEX_ASC_ASC
(
    COL_1 VARCHAR(10) NOT NULL,
    COL_2 VARCHAR(10) NOT NULL
)
/
CREATE UNIQUE INDEX TEST.UNIQUE_IDX_ASC_ASC ON TEST.UNIQUE_INDEX_ASC_ASC (COL_1 ASC, COL_2 ASC)
/