DROP TABLE IF EXISTS TEST.BINARY_DATA_TYPES
/
CREATE TABLE TEST.BINARY_DATA_TYPES
(
    -- with default size of 1 character
    BINARY_COL                    BINARY,
    -- BINARY VARYING must have a size,
    -- VARBINARY must have a size,
    CHAR_FOR_BIT_DATA_COL         CHAR FOR BIT DATA,
    CHARACTER_FOR_BIT_DATA_COL    CHARACTER FOR BIT DATA,
    -- CHAR VARYING must have a size,
    -- CHARACTER VARYING must have a size
    GRAPHIC_COL                   GRAPHIC,
    -- VARGRAPHIC must have a size,

    -- with internal size of 37200 character
    LONG_VARCHAR_COL LONG VARCHAR FOR BIT DATA,

    -- with default size of 1048576 character
    BLOB_COL BLOB,

    -- with minimum size of 1 character
    BINARY_1_COL                  BINARY(1),
    BINARY_VARYING_1_COL          BINARY VARYING(1),
    VARBINARY_1_COL               VARBINARY(1),

    CHAR_1_FOR_BIT_DATA_COL             CHAR(1) FOR BIT DATA,
    CHAR_1_OCTETS_FOR_BIT_DATA_COL      CHAR(1 OCTETS) FOR BIT DATA,

    CHARACTER_1_FOR_BIT_DATA_COL        CHARACTER(1) FOR BIT DATA,
    CHARACTER_1_OCTETS_FOR_BIT_DATA_COL CHARACTER(1 OCTETS) FOR BIT DATA,

    CHAR_VARYING_1_FOR_BIT_DATE_COL        CHAR VARYING(1)  FOR BIT DATA,
    CHAR_VARYING_1_OCTETS_FOR_BIT_DATA_COL CHAR VARYING(1 OCTETS)  FOR BIT DATA,

    CHARACTER_VARYING_1_FOR_BIT_DATA_COL        CHARACTER VARYING(1) FOR BIT DATA,
    CHARACTER_VARYING_1_OCTETS_FOR_BIT_DATA_COL CHARACTER VARYING(1 OCTETS) FOR BIT DATA,

    VARCHAR_1_FOR_BIT_DATA_COL        VARCHAR(1) FOR BIT DATA,
    VARCHAR_1_OCTETS_FOR_BIT_DATA_COL VARCHAR(1 OCTETS) FOR BIT DATA,

    GRAPHIC_1_COL                GRAPHIC(1),
    GRAPHIC_1_CODEUNITS16_COL    GRAPHIC(1 CODEUNITS16),
    GRAPHIC_1_CODEUNITS32_COL    GRAPHIC(1 CODEUNITS32),

    VARGRAPHIC_1_COL             VARGRAPHIC(1),
    VARGRAPHIC_1_CODEUNITS16_COL VARGRAPHIC(1 CODEUNITS16),
    VARGRAPHIC_1_CODEUNITS32_COL VARGRAPHIC(1 CODEUNITS32),

    BLOB_1_COL BLOB(1),

    -- with maximum size
    BINARY_255_COL           BINARY(255),
    BINARY_VARYING_32672_COL BINARY VARYING(32672),
    VARBINARY_32672_COL      VARBINARY(32672),

    CHAR_255_FOR_BIT_DATA_COL      CHAR(255) FOR BIT DATA,
    CHARACTER_255_FOR_BIT_DATA_COL CHARACTER(255) FOR BIT DATA,

    VARCHAR_32762_FOR_BIT_DATA_COL        VARCHAR(32672) FOR BIT DATA,
    VARCHAR_32762_OCTETS_FOR_BIT_DATA_COL VARCHAR(32672 OCTETS) FOR BIT DATA,

    CHAR_VARYING_255_FOR_BIT_DATE_COL        CHAR VARYING(255)  FOR BIT DATA,
    CHAR_VARYING_255_OCTETS_FOR_BIT_DATA_COL CHAR VARYING(255 OCTETS)  FOR BIT DATA,

    CHARACTER_VARYING_255_FOR_BIT_DATA_COL        CHARACTER VARYING(255) FOR BIT DATA,
    CHARACTER_VARYING_255_OCTETS_FOR_BIT_DATA_COL CHARACTER VARYING(255 OCTETS) FOR BIT DATA,

    GRAPHIC_127_COL             GRAPHIC(127),
    GRAPHIC_127_CODEUNITS16_COL GRAPHIC(127 CODEUNITS16),
    GRAPHIC_127_CODEUNITS32_COL GRAPHIC(63 CODEUNITS32),

    BLOB_2147483647_COL         BLOB(2147483647)

)