BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEST.ANY_DATA_TYPES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE TEST.ANY_DATA_TYPES
(
    ANYTYPE_COL    ANYTYPE,
    ANYDATASET_COL ANYDATASET

)