BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEST.ARRAY_DATA_TYPES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
-- drop TEST.VARRAY_5_VARRAY_5_VARCHAR2_50_TYPE which is based on TEST.VARRAY_5_VARCHAR2_50_TYPE
BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE TEST.VARRAY_5_VARRAY_5_VARCHAR2_50_TYPE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN -- Fehlercode -4043 = ORA-04043: Object does not exist
            RAISE; -- Fehler erneut auslösen, wenn es ein anderer Fehler ist
        END IF;
END;
/
CREATE OR REPLACE TYPE TEST.VARRAY_5_VARCHAR2_50_TYPE AS VARRAY(5) OF VARCHAR2(50);
/
CREATE OR REPLACE TYPE TEST.VARRAY_5_NUMBER_2_1_TYPE AS VARRAY(5) OF NUMBER(2, 1);
/
CREATE OR REPLACE TYPE TEST.VARRAY_5_TIMESTAMP_3_TYPE AS VARRAY(5) OF TIMESTAMP(3);
/
CREATE OR REPLACE TYPE TEST.VARRAY_5_INTERVAL_DAY_3_TO_SECOND_1_TYPE AS VARRAY(5) OF INTERVAL DAY(3) TO SECOND(1);
/
CREATE OR REPLACE TYPE TEST.VARRAY_5_SDO_GEOMETRY_TYPE AS VARRAY(5) OF SDO_GEOMETRY;
/
CREATE OR REPLACE TYPE TEST.VARRAY_5_ANYTYPE_TYPE AS VARRAY(5) OF ANYTYPE;
/
CREATE OR REPLACE TYPE TEST.VARRAY_5_BFILE_TYPE AS VARRAY(5) OF BFILE;
/
CREATE OR REPLACE TYPE TEST.VARRAY_5_VARRAY_5_VARCHAR2_50_TYPE AS VARRAY(5) OF TEST.VARRAY_5_VARCHAR2_50_TYPE;

-- No VARAY for XMLTYPE, ROWID and UROWID
/
CREATE TABLE TEST.ARRAY_DATA_TYPES
(

    VARRAY_5_VARCHAR2_50_COL                TEST.VARRAY_5_VARCHAR2_50_TYPE,
    VARRAY_5_NUMBER_2_1_COL                 TEST.VARRAY_5_NUMBER_2_1_TYPE,
    VARRAY_5_TIMESTAMP_3_COL                TEST.VARRAY_5_TIMESTAMP_3_TYPE,
    VARRAY_5_INTERVAL_DAY_3_TO_SECOND_1_COL TEST.VARRAY_5_INTERVAL_DAY_3_TO_SECOND_1_TYPE,
    VARRAY_5_SDO_GEOMETRY_COL               TEST.VARRAY_5_SDO_GEOMETRY_TYPE,
    VARRAY_5_ANYTYPE_COL                    TEST.VARRAY_5_ANYTYPE_TYPE,
    VARRAY_5_BFILE_COL                      TEST.VARRAY_5_BFILE_TYPE,
    VARRAY_5_VARRAY_5_VARCHAR2_50_TYPE      TEST.VARRAY_5_VARRAY_5_VARCHAR2_50_TYPE


)