BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEST.BINARY_DATA_TYPES PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE TEST.BINARY_DATA_TYPES
(
    RAW_1_COL    RAW(1),
    RAW_2000_COL RAW(2000),

    LONG_RAW_COL LONG RAW,
    BLOB_COL     BLOB

)
