BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEST.GEOMETRY_DATA_TYPES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE TEST.GEOMETRY_DATA_TYPES
(
    SDO_GEOMETRY_COL             SDO_GEOMETRY,
    SDO_TOPO_GEOMETRY_COL        SDO_TOPO_GEOMETRY,

    SDO_GEOR_HISTOGRAM_COL       SDO_GEOR_HISTOGRAM,
    SDO_GEOR_HISTOGRAM_ARRAY_COL SDO_GEOR_HISTOGRAM_ARRAY,

    SDO_GEOR_COLORMAP_COL        SDO_GEOR_COLORMAP,
    --SDO_GEOR_GRAYSCALE_COL       SDO_GEOR_GRAYSCALE,

    --SDO_RASTERSET_COL            SDO_RASTERSET,

    SDO_RANGE_COL                SDO_RANGE,

    SDO_RANGE_ARRAY_COL          SDO_RANGE_ARRAY,
    SDO_RASTER_COL               SDO_RASTER,
    SDO_GEOR_SRS_COL             SDO_GEOR_SRS,

    SDO_GEOR_GCP_COL             SDO_GEOR_GCP,
    SDO_GEOR_GCPGEOREFTYPE_COL   SDO_GEOR_GCPGEOREFTYPE,
    SDO_GEOR_GCP_COLLECTION_COL  SDO_GEOR_GCP_COLLECTION

)