BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEST.INTERVAL_DATA_TYPES PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE TEST.INTERVAL_DATA_TYPES
(
    INTERVAL_YEAR_TO_MONTH_COL     INTERVAL YEAR TO MONTH,
    INTERVAL_YEAR_TO_MONTH_1_COL   INTERVAL YEAR(1) TO MONTH,
    INTERVAL_YEAR_TO_MONTH_2_COL   INTERVAL YEAR(2) TO MONTH,
    INTERVAL_YEAR_TO_MONTH_9_COL   INTERVAL YEAR(9) TO MONTH,

    INTERVAL_DAY_TO_SECOND_COL     INTERVAL DAY TO SECOND,

    INTERVAL_DAY_0_TO_SECOND_COL   INTERVAL DAY(0) TO SECOND,
    INTERVAL_DAY_2_TO_SECOND_COL   INTERVAL DAY(2) TO SECOND,
    INTERVAL_DAY_9_TO_SECOND_COL   INTERVAL DAY(9) TO SECOND,

    INTERVAL_DAY_TO_SECOND_0_COL   INTERVAL DAY TO SECOND(0),
    INTERVAL_DAY_TO_SECOND_6_COL   INTERVAL DAY TO SECOND(6),
    INTERVAL_DAY_TO_SECOND_9_COL   INTERVAL DAY TO SECOND(9),

    INTERVAL_DAY_0_TO_SECOND_0_COL INTERVAL DAY(0) TO SECOND(0),
    INTERVAL_DAY_0_TO_SECOND_6_COL INTERVAL DAY(0) TO SECOND(6),
    INTERVAL_DAY_0_TO_SECOND_9_COL INTERVAL DAY(0) TO SECOND(9),

    INTERVAL_DAY_2_TO_SECOND_0_COL INTERVAL DAY(2) TO SECOND(0),
    INTERVAL_DAY_2_TO_SECOND_6_COL INTERVAL DAY(2) TO SECOND(6),
    INTERVAL_DAY_2_TO_SECOND_9_COL INTERVAL DAY(2) TO SECOND(9),

    INTERVAL_DAY_9_TO_SECOND_0_COL INTERVAL DAY(9) TO SECOND(0),
    INTERVAL_DAY_9_TO_SECOND_6_COL INTERVAL DAY(9) TO SECOND(6),
    INTERVAL_DAY_9_TO_SECOND_9_COL INTERVAL DAY(9) TO SECOND(9)

)