BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEST.TEMPORAL_DATA_TYPES PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE TEST.TEMPORAL_DATA_TYPES
(
    DATE_COL             DATE,

    TIMESTAMP_COL        TIMESTAMP,
    TIMESTAMP_0_COL      TIMESTAMP(0),
    TIMESTAMP_1_COL      TIMESTAMP(1),
    TIMESTAMP_9_COL      TIMESTAMP(9),

    TIMESTAMP_WTZ_COL    TIMESTAMP WITH TIME ZONE,
    TIMESTAMP_0_WTZ_COL  TIMESTAMP(0) WITH TIME ZONE,
    TIMESTAMP_1_WTZ_COL  TIMESTAMP(1) WITH TIME ZONE,
    TIMESTAMP_9_WTZ_COL  TIMESTAMP(9) WITH TIME ZONE,

    TIMESTAMP_WLTZ_COL   TIMESTAMP WITH LOCAL TIME ZONE,
    TIMESTAMP_0_WLTZ_COL TIMESTAMP(0) WITH LOCAL TIME ZONE,
    TIMESTAMP_1_WLTZ_COL TIMESTAMP(1) WITH LOCAL TIME ZONE,
    TIMESTAMP_9_WLTZ_COL TIMESTAMP(9) WITH LOCAL TIME ZONE

)