DROP TABLE IF EXISTS TEST.COLUMN_DEFAULTS
/
CREATE TABLE TEST.COLUMN_DEFAULTS
(
    VARCHAR_10_DEFAULT_TEXT_COL             VARCHAR(10) DEFAULT 'TEXT',
    DECIMAL_10_2_DEFAULT_1_23_COL           DECIMAL(10, 2) DEFAULT 1.23,
    TIMESTAMP_DEFAULT_CURRENT_TIMESTAMP_COL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BOOLEAN_DEFAULT_FALSE_COL               BOOLEAN DEFAULT FALSE,
    "BOOLEAN_DEFAULT_true_COL"              BOOLEAN DEFAULT true,
    INTEGER_DEFAULT_NULL_COL                INTEGER DEFAULT NULL
)