DROP TABLE IF EXISTS TEST.COMMENTS
/
CREATE TABLE TEST.COMMENTS
(
    COMMENT_COL VARCHAR(10)
)
/
COMMENT ON TABLE TEST.COMMENTS IS 'This is a table comment'
/
COMMENT ON COLUMN TEST.COMMENTS.COMMENT_COL IS 'This is a column comment'
